import Link from 'next/link'
import { ArrowRight, Building2, Handshake, BriefcaseBusiness, ScanLine, Stethoscope, Microscope, Pill, HeartPulse, Users } from 'lucide-react'
import { Header, Footer, Card, CTA } from './components'

const services = [
 ['GP Clinics','Modern general practice environments designed for patient access, operational efficiency and integrated referral pathways.'],
 ['Imaging & Diagnostics','Future-ready infrastructure planning for MRI, CT, diagnostic imaging, power, shielding and clinical workflow.'],
 ['Specialist Suites','Premium specialist consulting environments for independent specialists, multi-disciplinary groups and sessional use.'],
 ['Pathology','Integrated pathology services supporting patient convenience and clinical ecosystem efficiency.'],
 ['Pharmacy','Strategic pharmacy integration to support patients, operators and precinct performance.'],
 ['Allied Health','Flexible tenancy and partnership options within a coordinated healthcare destination.']
]

export default function Home(){return <><Header/><main>
<section className="relative overflow-hidden bg-gradient-to-br from-slate-950 via-slate-900 to-slate-800 px-6 py-24 text-white md:py-32"><div className="absolute right-[-10%] top-[-20%] h-96 w-96 rounded-full bg-cyan-300/20 blur-3xl"/><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[1.1fr_0.9fr] md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.35em] text-cyan-200">Healthcare Platform</p><h1 className="mt-6 max-w-4xl text-5xl font-semibold tracking-tight md:text-7xl">Healthcare Property. Clinical Partnerships. Long-Term Platform Value.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-300 md:text-xl">GrandMed develops next-generation healthcare precincts across Australia, bringing together healthcare real estate, clinical partnerships, specialist ecosystems and strategic operating platforms.</p><div className="mt-10 flex flex-col gap-4 sm:flex-row"><Link href="/projects" className="inline-flex items-center justify-center rounded-2xl bg-white px-7 py-4 font-semibold text-slate-950 shadow-lg">View Projects <ArrowRight className="ml-2 h-5 w-5"/></Link><Link href="/partnerships" className="inline-flex items-center justify-center rounded-2xl border border-white/20 px-7 py-4 font-semibold text-white">Healthcare Partnerships</Link></div></div><div className="rounded-[2.5rem] border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur"><div className="rounded-[2rem] bg-white p-6 text-slate-950"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">Flagship Focus</p><h2 className="mt-2 text-3xl font-semibold">Kingston Healthcare Precinct</h2><p className="mt-5 leading-7 text-slate-600">A premium Canberra healthcare destination planned for GP, specialists, imaging, pathology, pharmacy, allied health and future procedural capability.</p><div className="mt-6 grid gap-3">{['Clinical functionality','Patient accessibility','Specialist clustering','Future-ready infrastructure'].map(x=><div key={x} className="rounded-2xl bg-slate-50 p-4 font-medium">{x}</div>)}</div></div></div></div></section>
<section className="px-6 py-20"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-500">Our Vision</p><h2 className="mt-4 text-4xl font-semibold tracking-tight md:text-5xl">Australia’s leading integrated healthcare precinct platform.</h2></div><div className="space-y-6 text-lg leading-8 text-slate-600"><p>GrandMed is focused on building healthcare environments that support patients, practitioners, operators and investors through high-quality, future-ready medical precincts.</p><p>Backed by GranDev, GrandMed combines premium healthcare real estate with strategic healthcare operating partnerships.</p></div></div></section>
<section className="bg-white px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[0.25em] text-slate-500">Healthcare Ecosystem</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight md:text-5xl">Designed around the services patients and practitioners need.</h2><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map(([title,text])=><Card key={title} title={title} text={text}/>)}</div></div></section>
<section className="px-6 py-20"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><Link href="/projects" className="rounded-[2rem] bg-white p-8 shadow-sm"><Building2 className="mb-5 h-10 w-10"/><h3 className="text-2xl font-semibold">Projects</h3><p className="mt-3 text-slate-600">Kingston flagship and future expansion pipeline.</p></Link><Link href="/partnerships" className="rounded-[2rem] bg-slate-950 p-8 text-white shadow-sm"><Handshake className="mb-5 h-10 w-10"/><h3 className="text-2xl font-semibold">Partnerships</h3><p className="mt-3 text-slate-300">Operator, imaging, GP, specialist and allied health partnerships.</p></Link><Link href="/investors" className="rounded-[2rem] bg-white p-8 shadow-sm"><BriefcaseBusiness className="mb-5 h-10 w-10"/><h3 className="text-2xl font-semibold">Investors</h3><p className="mt-3 text-slate-600">Healthcare property and long-term platform value.</p></Link></div></section>
<CTA/></main><Footer/></>}
